#!/bin/bash
FILES=./bus96in24hour/*
for f in $FILES
do
	echo ${f:16}
	while read line;do
		echo "INSERT INTO stop_time(route_id, stop_id, time) VALUES(2,'${f:16}','$line');" > ./insert.sql
	mysql -u crowdapp -pcs3282 crowd_db < ./insert.sql
	done < "$f"
done