#!/bin/bash
while read line;do
	echo "INSERT INTO stop_time(route_id, stop_id, time) VALUES(1,'$1','$line');" > insert.sql
mysql -u crowdapp -h cloudappserver-i.comp.nus.edu.sg -pcs3282 crowd_db < insert.sql
done < "$1"
